### ISSUE TITLE
readme does not tell what should I run and in which order

### ISSUE THREAD

**Issue by ares** [lzap/foreman-elasticsearch#3]
I have no idea how to use this repo :-)

**Comment by lzap** [comment]
Sorry what? Follow the whole document, if something is not clear report specific case please.

**Comment by ares** [comment]
I think it would be beneficial to start with a paragraph what is this all about and what it in fact installs and configured. By starting reading the readme, I was confused until I reached to "Configuring Elasticsearch and Kibana" where the instructions starts.

Something like, this readme contains steps to install ELK stack and configure Foreman/Satellite to log to it... also it would be great to have numbered steps to better relate to them and to make it clear, this is step by step setup.
