### ISSUE TITLE
Candlepin upgrading logstash version

### ISSUE THREAD

**Issue by nikosmoum** [lzap/foreman-elasticsearch#9]
This is a heads up that Candlepin 4.0 and 4.1 will be upgrading to logstash 7.0.1 which has some non-backwards compatible changes, so the candlepin.xml syslog JSON config here will likely break. Not opening a PR because I don't know the exact config requirements you have, but the example added [here](https://github.com/candlepin/candlepin/pull/3191/files#diff-33255c198beb505875429994308ac79fd2a34e56bf81f6a7794dec3687790441R71-R81) worked for me.

**Comment by lzap** [comment]
Thanks, I dropped a note in: a1d7be4cfd39ff1d2e6d026e87394780137b2ad5
